const model = {
    currentPage: 'home',
    view: '',
    spells: {
        druid: {
            healing: [
                { spell: "Exura sio 'Yakubu' ", healing: 70 },
                { spell: "Exura vita", healing: 70 },
                { spell: "Exana kor", healing: 70 },
                { spell: "Exana flam", healing: 70 },
                { spell: "Exana pox", healing: 70 },
                { spell: "Exura gran", healing: 70 },
                { spell: "Exura", healing: 70 },
                { spell: "Exura infir", healing: 70 },
                { spell: "Exura gran mas res", healing: 70 },
                { spell: "Exura gran sio para", healing: 70 },
                { spell: "Exura max vita", healing: 70 }
            ],
            attacks: [
                { spell: "exori min flam" },
                { spell: "exevo infir frigo hur" },
                { spell: "exori vis" },
                { spell: "utori pox" },
                { spell: "exevo gran mas frigo" },
                { spell: "exori flam" },
                { spell: "exori frigo" },
                { spell: "exevo frigo hur" },
                { spell: "exori infir tera" },
                { spell: "exori moe ico" },
                { spell: "exori gran frigo" },
                { spell: "exevo gran frigo hur" },
                { spell: "exori gran tera" },
                { spell: "exori tera" },
                { spell: "exevo tera hur" },
                { spell: "exori max frigo" },
                { spell: "exori max tera" },
                { spell: "exevo gran mas tera" },
            ],
            support: [
                { spell: "exana vita" },
                { spell: "utevo res ina 'Monk'" },
                { spell: "exiva moe res" },
                { spell: "exiva 'Yakubu'" },
                { spell: "exevo pan" },
                { spell: "utevo gran lux" },
                { spell: "utani hur" },
                { spell: "utura mas sio" },
                { spell: "utana vid" },
                { spell: "exani hur 'up'" },
                { spell: "exani hur 'down'" },
                { spell: "utevo lux" },
                { spell: "exani tera" },
                { spell: "utamo vita" },
                { spell: "utani gran hur" },
                { spell: "utevo res 'Monk'" },
                { spell: "utevo gran res dru" },
                { spell: "utevo vis lux" },
            ],
            runes: [
                { spell: "adana mort" },
                { spell: "adori mas frigo" },
                { spell: "adevo ina" },
                { spell: "adeta sio" },
                { spell: "adana pox" },
                { spell: "adito grav" },
                { spell: "adito tera" },
                { spell: "adevo grav vis" },
                { spell: "adevo mas grav vis" },
                { spell: "adevo mas hur" },
                { spell: "adevo mas flam" },
                { spell: "adevo grav flam" },
                { spell: "adevo mas grav flam" },
                { spell: "adori vis" },
                { spell: "adori frigo" },
                { spell: "adura gran" },
                { spell: "adori min vis" },
                { spell: "adana ani" },
                { spell: "adevo mas pox" },
                { spell: "adevo grav pox" },
                { spell: "adevo mas grav pox" },
                { spell: "adevo res flam" },
                { spell: "adori tera" },
                { spell: "adori mas tera" },
                { spell: "adura vita" },
                { spell: "adevo grav vita" },
            ],
        },
        sorcerer: {
            healing: [
                { spell: "exana pox" },
                { spell: "exura gran" },
                { spell: "exura" },
                { spell: "exura vita" },
                { spell: "exura infir" },
                { spell: "exura max vita" },
            ],
            attacks: [
                { spell: "exori min flam" },
                { spell: "exori infir vis" },
                { spell: "utori mort" },
                { spell: "exori mort" },
                { spell: "utori vis" },
                { spell: "exevo vis lux" },
                { spell: "exori vis" },
                { spell: "exevo vis hur" },
                { spell: "exevo flam hur" },
                { spell: "exori flam" },
                { spell: "exevo gran vis lux" },
                { spell: "exevo gran flam hur" },
                { spell: "exevo gran mas flam" },
                { spell: "exori frigo" },
                { spell: "utori flam" },
                { spell: "exori amp vis" },
                { spell: "exevo gran mas vis" },
                { spell: "exevo infir flam hur" },
                { spell: "exori gran vis" },
                { spell: "exori gran flam" },
                { spell: "exori tera" },
                { spell: "exori max vis" },
                { spell: "exori max flam" },
            ],
            support: [
                { spell: "exana vita" },
                { spell: "exevo gran mort" },
                { spell: "utevo res ina 'Monk'" },
                { spell: "utori mas sio" },
                { spell: "exori moe" },
                { spell: "exiva moe res" },
                { spell: "exiva 'Yakubu'" },
                { spell: "utevo gran lux" },
                { spell: "utani hur" },
                { spell: "utana vid" },
                { spell: "exani hur 'up'" },
                { spell: "exani hur 'down'" },
                { spell: "utevo lux" },
                { spell: "exani tera" },
                { spell: "utamo vita" },
                { spell: "exori kor" },
                { spell: "utani gran hur" },
                { spell: "utevo res 'Monk'" },
                { spell: "utevo gran res ven'" },
                { spell: "utevo vis lux" },
            ],
            runes: [
                { spell: "adana mort" },
                { spell: "adito grav" },
                { spell: "adito tera" },
                { spell: "adevo mas vis" },
                { spell: "adevo grav vis" },
                { spell: "adevo mas grav vis" },
                { spell: "adevo mas hur" },
                { spell: "adevo mas flam" },
                { spell: "adevo grav flam" },
                { spell: "adevo mas grav flam" },
                { spell: "adori flam" },
                { spell: "adori mas flam" },
                { spell: "adori vis" },
                { spell: "adori min vis" },
                { spell: "adevo grav tera" },
                { spell: "adevo grav pox" },
                { spell: "adevo mas grav pox" },
                { spell: "adevo res flam" },
                { spell: "adori tera" },
                { spell: "adori gran mort" },
                { spell: "adori mas vis" },
            ],
        },
        paladin: {
            healing: [
                { spell: "exana mort" },
                { spell: "exana pox" },
                { spell: "exura san" },
                { spell: "exura gran" },
                { spell: "utura gran" },
                { spell: "exura" },
                { spell: "exura infir" },
                { spell: "utura" },
                { spell: "exura gran san" },
            ],
            attacks: [
                { spell: "exevo mas san" },
                { spell: "exori san" },
                { spell: "exori con" },
                { spell: "utori san" },
                { spell: "exori gran con" },
            ],
            support: [
                { spell: "exevo infir con" },
                { spell: "exana ina" },
                { spell: "exevo con" },
                { spell: "exevo con flam" },
                { spell: "exana amp res" },
                { spell: "exeta con" },
                { spell: "exiva moe res" },
                { spell: "exiva 'Yakubu'" },
                { spell: "utevo gran lux" },
                { spell: "utani hur" },
                { spell: "exani hur 'up'" },
                { spell: "exani hur 'down'" },
                { spell: "utevo lux" },
                { spell: "exani tera" },
                { spell: "utamo mas sio" },
                { spell: "utito tempo san" },
                { spell: "utevo gran res sac" },
                { spell: "utamo tempo san" },
            ],
            runes: [
                { spell: "adito grav" },
                { spell: "adito tera" },
                { spell: "adori san" },
            ],
        },
        knight: {
            healing: [
                { spell: "exura infir ico" },
                { spell: "exana kor" },
                { spell: "exana pox" },
                { spell: "exura med ico" },
                { spell: "utura gran" },
                { spell: "exura gran ico" },
                { spell: "utura" },
                { spell: "exura ico" },
            ],
            attacks: [
                { spell: "exori gran ico" },
                { spell: "exori" },
                { spell: "exori ico" },
                { spell: "exori gran" },
                { spell: "exori min" },
                { spell: "exori mas" },
                { spell: "exori hur" },
                { spell: "utori kor" },
            ],
            support: [
                { spell: "utito tempo" },
                { spell: "exeta res" },
                { spell: "utani tempo hur" },
                { spell: "exeta amp res" },
                { spell: "exiva moe res" },
                { spell: "exiva 'Yakubu'" },
                { spell: "utevo gran lux" },
                { spell: "utani hur" },
                { spell: "exani hur 'up'" },
                { spell: "exani hur 'down'" },
                { spell: "utevo lux" },
                { spell: "exani tera" },
                { spell: "utamo tempo" },
                { spell: "utevo gran res eq" },
                { spell: "utito mas sio" },
            ],
        }
    }



}
//Druid
let druidSpellsR = '';
let druidSpellsA = '';
let druidSpellsH = '';
let druidSpellsS = '';


//Knight
let knightSpellsA = '';
let knightSpellsH = '';
let knightSpellsS = '';


//Paladin
let paladinSpellsA = '';
let paladinSpellsH = '';
let paladinSpellsR = '';
let paladinSpellsS = '';


//Sorcerer
let sorcererSpellsA = '';
let sorcererSpellsH = '';
let sorcererSpellsR = '';
let sorcererSpellsS = '';
